# Generated by Django 5.2.7 on 2026-02-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_commande_options_commande_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ecole/')),
                ('image_classes', models.ImageField(blank=True, null=True, upload_to='ecole/')),
                ('description_classes', models.TextField(blank=True, null=True)),
                ('image_cour', models.ImageField(blank=True, null=True, upload_to='ecole/')),
                ('description_cour', models.TextField(blank=True, null=True)),
                ('image_profs', models.ImageField(blank=True, null=True, upload_to='ecole/')),
                ('description_profs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
