# Generated by Django 5.2.7 on 2026-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ecole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('formation', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
