# Generated by Django 5.2.7 on 2026-02-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_homedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('responsable', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
            ],
        ),
    ]
