# Generated by Django 5.2.7 on 2026-02-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('lien_passage', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificats/')),
            ],
        ),
    ]
