# Generated by Django 5.2.7 on 2026-02-18 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_certificat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificat',
            name='details',
        ),
        migrations.RemoveField(
            model_name='certificat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='certificat',
            name='lien_passage',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('certificat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.certificat')),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('certificat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.certificat')),
            ],
        ),
    ]
