# Generated by Django 5.2.7 on 2026-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_certificat_details_remove_certificat_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificats/'),
        ),
        migrations.AddField(
            model_name='certificat',
            name='lien_passage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
