# Generated by Django 5.2.7 on 2026-02-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_certificat_details_certificat_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='associations/'),
        ),
    ]
