# Generated by Django 5.2.7 on 2026-02-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_association_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
