# Generated by Django 5.2.7 on 2026-02-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_association_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_event', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='myapp.association')),
            ],
        ),
    ]
