# Generated by Django 5.2.7 on 2026-02-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscription',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
