# Generated by Django 5.2.7 on 2026-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_preinscription_commune_preinscription_quartier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('type_filiere', models.CharField(choices=[('tertiaire', 'Tertiaire'), ('industrielle', 'Industrielle')], max_length=20)),
            ],
        ),
    ]
