# Generated by Django 5.2.7 on 2026-02-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formations/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
