# Generated by Django 5.2.7 on 2026-02-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_formation_image_alter_formation_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='details',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='titre',
        ),
        migrations.AddField(
            model_name='formation',
            name='nom',
            field=models.CharField(default='Moussa', max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='type_filiere',
            field=models.CharField(default='tertiaire ou industrielle', max_length=50),
        ),
    ]
