# Generated by Django 5.2.7 on 2026-02-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_formation_details_remove_formation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='nom',
        ),
        migrations.AddField(
            model_name='formation',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formations/'),
        ),
        migrations.AddField(
            model_name='formation',
            name='titre',
            field=models.CharField(default='Formation par défaut', max_length=200),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(default='Nouvelle formation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formation',
            name='type_filiere',
            field=models.CharField(choices=[('tertiaire', 'Filière Tertiaire'), ('industrielle', 'Filière Industrielle')], default='tertiaire', max_length=50),
        ),
    ]
