# Generated by Django 5.2.7 on 2026-02-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_formation_nom_formation_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement_inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
