# Generated by Django 5.2.7 on 2026-02-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_evenement_inst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement_inst',
            name='date_creation',
        ),
    ]
