# Generated by Django 5.2.7 on 2026-03-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_evenement_inst_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='type_filiere',
            field=models.CharField(choices=[('tertiaire', 'Filière Tertiaire'), ('industrielle', 'Filière Industrielle'), ('industrielle', 'Année Preparatoire')], default='tertiaire', max_length=50),
        ),
    ]
