# Generated by Django 5.2.7 on 2026-03-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_formation_type_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleIngenieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Formation par défaut', max_length=200)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('type_cycle', models.CharField(choices=[('licence', 'Licence'), ('master1', 'Master 1'), ('master2', 'Master 2')], default='licence', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cycles/')),
            ],
        ),
    ]
