# Generated by Django 5.2.7 on 2026-03-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_cycleingenieur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleingenieur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cycle_ingenieur/'),
        ),
        migrations.AlterField(
            model_name='cycleingenieur',
            name='titre',
            field=models.CharField(default='Formation Cycle Ingénieur', max_length=200),
        ),
    ]
