# Generated by Django 5.2.7 on 2026-03-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_cycleingenieur_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscription',
            name='adresse_parents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='annee_obtention',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='diplome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='etablissement_origine',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='piece_recto',
            field=models.ImageField(blank=True, null=True, upload_to='pieces/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='piece_verso',
            field=models.ImageField(blank=True, null=True, upload_to='pieces/'),
        ),
        migrations.AddField(
            model_name='preinscription',
            name='telephone_pere',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
