# Generated by Django 5.2.7 on 2026-03-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_preinscription_adresse_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_etudiants/'),
        ),
    ]
