# Generated by Django 5.2.7 on 2026-03-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_preinscription_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=50)),
                ('formation', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('etablissement_origine', models.CharField(max_length=150)),
                ('diplome', models.CharField(max_length=100)),
                ('annee_obtention', models.IntegerField()),
                ('nom_pere', models.CharField(max_length=100)),
                ('telephone_pere', models.CharField(max_length=20)),
                ('adresse_parents', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_etudiants/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
