# Generated by Django 5.2.7 on 2026-03-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='piece_recto',
            field=models.ImageField(blank=True, null=True, upload_to='inscriptions/'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='piece_verso',
            field=models.ImageField(blank=True, null=True, upload_to='inscriptions/'),
        ),
    ]
