# Generated by Django 5.2.7 on 2026-03-04 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_inscription_message_inscription_piece_recto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
