# Generated by Django 5.2.7 on 2026-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_inscription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='identifiant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
    ]
