# Generated by Django 5.2.7 on 2026-03-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_inscription_identifiant_inscription_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='type_filiere',
            field=models.CharField(choices=[('bts', 'BTS (BAC+2)'), ('licence', 'Licence (BAC+3)'), ('master', 'Master (BAC+5)'), ('ingenieur', 'Cycle Ingénieur (BAC+5)'), ('business', 'Business School (EMBS)'), ('preparatoire', 'Année Préparatoire')], default='bts', max_length=50),
        ),
    ]
