# Generated by Django 5.2.7 on 2026-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_formation_type_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='E3MSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Formation E3M', max_length=200)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('type_filiere', models.CharField(choices=[('bts', 'BTS (BAC+2)'), ('licence', 'Licence (BAC+3)'), ('master', 'Master (BAC+5)'), ('ingenieur', 'Cycle Ingénieur (BAC+5)'), ('preparatoire', 'Année Préparatoire')], default='bts', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='e3m_formations/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('piece_recto', models.ImageField(blank=True, null=True, upload_to='inscriptions/')),
                ('piece_verso', models.ImageField(blank=True, null=True, upload_to='inscriptions/')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=50)),
                ('formation', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('etablissement_origine', models.CharField(max_length=150)),
                ('diplome', models.CharField(max_length=100)),
                ('annee_obtention', models.IntegerField()),
                ('nom_pere', models.CharField(max_length=100)),
                ('telephone_pere', models.CharField(max_length=20)),
                ('adresse_parents', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_etudiants/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='piece_recto',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='piece_verso',
        ),
        migrations.AlterField(
            model_name='inscription',
            name='adresse_parents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='annee_obtention',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='diplome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etablissement_origine',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nationalite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='telephone_pere',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
