# Generated by Django 5.2.7 on 2026-03-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_e3mschool_remove_inscription_piece_recto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e3mschool',
            name='adresse_parents',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='annee_obtention',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='date_inscription',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='diplome',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='email',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='etablissement_origine',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='message',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='nom_pere',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='piece_recto',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='piece_verso',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='e3mschool',
            name='telephone_pere',
        ),
    ]
