# Generated by Django 5.2.7 on 2026-03-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_e3mschool_adresse_parents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
