# Generated by Django 5.2.7 on 2026-03-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_galerie'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='galerie/videos/'),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='galerie/'),
        ),
    ]
